if [ -f /etc/bashrc ]; then
 . /etc/bashrc
fi

alias ll='ls -Al'
alias s='cd ..'

export EDITOR=vim

if [ -f $HOME/.git-prompt.sh ]; then
    source $HOME/.git-prompt.sh
    export PS1='\[\033[0;32m\]\[\033[0m\033[0;32m\]\u\[\033[0;36m\] @ \[\033[0;36m\]\h \w\[\033[0;32m\]$(__git_ps1)\n\[\033[0;32m\]└─\[\033[0m\033[0;32m\] \$\[\033[0m\033[0;32m\] ▶\[\033[0m\] '
fi
